### ISSUE TITLE
News Archive: Next page (page 2) is not found

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Danica-Carpentry#92]
URL links:
http://danica-carpentry-imp.stage.titanweb.com.au/news/
http://danica-carpentry-imp.stage.titanweb.com.au/news/page/2/

![image](https://cloud.githubusercontent.com/assets/12888048/16759417/5af05360-4849-11e6-8896-40fce2cfd41d.png)

**Comment by cyril-7175N** [comment]
Note: A redirect has been created ( /news/ to /category/news/ )so that the correct structure of the link is targeted. Currently, this permalink "http://danica-carpentry-imp.stage.titanweb.com.au/news/page/2/" won't work as it's not anymore following the wordpress template hierarchy and its resulting a 404 page.
